all:
	cd core && $(MAKE)
	cd lib && $(MAKE)
	@echo "############################################"
	@echo "#        z03 seems to be compiled !        #"
	@echo "# Check the ./bin folder and run ./z03-bot #"
	@echo "############################################"

clean:
	cd core && $(MAKE) clean
	cd lib && $(MAKE) clean

mrproper:
	cd core && $(MAKE) mrproper
	cd lib && $(MAKE) mrproper

install:
	cd core && $(MAKE) install
	cd lib && $(MAKE) install
