all:
	cd core && $(MAKE)
	cd lib && $(MAKE)

clean:
	cd core && $(MAKE) clean
	cd lib && $(MAKE) clean

mrproper:
	cd core && $(MAKE) mrproper
	cd lib && $(MAKE) mrproper

install:
	cd core && $(MAKE) install
	cd lib && $(MAKE) install
